name: rex-surrogate
channels:
  - defaults
dependencies:
  - python=3.6
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - nose=1.3.7
  - numpy=1.16.4
  - scipy=1.3.0
  - six=1.12.0
  - pip=19.1.1
  - pandas
  - pillow
  - dask
  - pip:
    - smt
    - pymks
    - seaborn
    - gpy==1.9.8
    - paramz==0.9.5
